apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stage-apps
  namespace: argocd
spec:
  generators:
    - git:
        revision: HEAD
        repoURL: git@github.com:vargaadam/k8s-ops.git
        directories:
          - path: cluster-components/architecture/*
  template:
    metadata:
      name: "stage-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: git@github.com:vargaadam/k8s-ops.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        name: civo-stage
        namespace: "{{path.basename}}"
