apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: v7m
  namespace: argocd
spec:
  destinations:
    - namespace: v7m
      server: https://212.2.242.14:6443
    - namespace: v7m
      server: https://212.2.242.239:6443
  sourceRepos:
    - git@github.com:vargaadam/k8s-ops.git
