apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: v7m
  namespace: argocd
spec:
  destinations:
  - namespace: v7m
    destination: https://212.2.243.55:6443
  - namespace: v7m
    destination: https://212.2.243.191:6443
  sourceRepos:
  - git@github.com:vargaadam/k8s-ops.git