apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-addons
  namespace: argocd
spec:
  generators:
    - git:
        revision: HEAD
        repoURL: git@github.com:vargaadam/k8s-ops.git
        directories:
          - path: cluster-components/architecture/*
          - path: cluster-components/provisioning/*
  template:
    metadata:
      name: "infra-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: git@github.com:vargaadam/k8s-ops.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        name: in-cluster
        namespace: "{{path.basename}}"
      ignoreDifferences:
        - kind: Secret
          name: infra-docker-registry-secret
          jsonPointers:
            - /data/htpasswd
            - /data/haSharedSecret
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
