apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-{{ .Values.alias }}
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    email: info@v7m.hu
    privateKeySecretRef:
      name: letsencrypt-prod-{{ .Values.alias }}
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage-{{ .Values.alias }}
  namespace: cert-manager
spec:
  acme:
    email: info@v7m.hu
    privateKeySecretRef:
      name: letsencrypt-stage-{{ .Values.alias }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
       ingress:
         class:  nginx